### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by Virnios** [DenialMC/Toontown-Crystal-New#2]
idk how to run it, teach me senpai

**Comment by DenialMC** [comment]
don't
it has a rat in it!!!!!!!!!!!1111111111111111111111111111111

**Comment by Virnios** [comment]
ok daddy

**Comment by DenialMC** [comment]
blame doritos or whatever his name is

**Comment by vincent15k** [comment]
doritos? o:

**Comment by Virnios** [comment]
i want doritos...

**Comment by vincent15k** [comment]
^^^^^^

**Comment by DenialMC** [comment]
yes d0ritos are gr8

**Comment by DenialMC** [comment]
especially custom ass instance ones

**Comment by vincent15k** [comment]
0mg denial mc th3 c0der///??///?!?1?!/11!?

**Comment by vincent15k** [comment]
and true

**Comment by DenialMC** [comment]
yes i make all the good shit that you steal 24/7

**Comment by DenialMC** [comment]
then u say OMG LETS FUCK UP STRIDE SO WE CAN ADVERTISE OUR GAYME WITH THEIR FEATURES

**Comment by DenialMC** [comment]
im telling u to the itnernet police

**Comment by vincent15k** [comment]
http://i.imgur.com/nSsfEsR.png oh yes yes

**Comment by DenialMC** [comment]
yup

**Comment by DenialMC** [comment]
600 of those commits are useless m8

**Comment by vincent15k** [comment]
omg totes!11!!!1

**Comment by Virnios** [comment]
FIGHT FIGHT FIGHT FIGHT FIGHT FIGHT FIGHT FIGHT

**Comment by DenialMC** [comment]
yup check it out

**Comment by vincent15k** [comment]
http://i.imgur.com/XK31eAD.png

**Comment by vincent15k** [comment]
spooked

**Comment by DenialMC** [comment]
thats my own code LMAO

**Comment by vincent15k** [comment]
oh totally!11!11

**Comment by DenialMC** [comment]
i can tell it by the 2 clubs

**Comment by DenialMC** [comment]
so stop ur bs

**Comment by vincent15k** [comment]
How exactly would I have access to your code?

**Comment by Virnios** [comment]
it's obvious LOL

**Comment by DenialMC** [comment]
please check it out

**Comment by DenialMC** [comment]
npcglove

**Comment by DenialMC** [comment]
TV

**Comment by DenialMC** [comment]
laff restock

**Comment by DenialMC** [comment]
delete all button

**Comment by DenialMC** [comment]
and 100 more features

**Comment by DenialMC** [comment]
all of those are mine

**Comment by DenialMC** [comment]
how? steve

**Comment by vincent15k** [comment]
It's song and dance attack, there are only so many ways to put it in.

**Comment by vincent15k** [comment]
And, I don't talk to steve

**Comment by DenialMC** [comment]
it's MY code fag I know I wrote it.

**Comment by DenialMC** [comment]
and your buddy threatened to leak the newest source even though this is it LOL

**Comment by DenialMC** [comment]
https://github.com/DenialMC/Toontown-Crystal-New/issues/1 i like this

**Comment by vincent15k** [comment]
Which?

**Comment by DenialMC** [comment]
one of ur 30 buddies

**Comment by vincent15k** [comment]
LOL

**Comment by vincent15k** [comment]
And, if it was your code, prove it. How would we have access?

**Comment by DenialMC** [comment]
who also happened to break into TTI for the exact same reason Pls.

**Comment by DenialMC** [comment]
IT'S MY CODE I don't care how you had access to it. You had. you stole it.

**Comment by DenialMC** [comment]
Look at that link I sent he's basically threatening and providing proof he has access. LMAO

**Comment by vincent15k** [comment]
I can confirm, we don't have access to any of your code.

**Comment by vincent15k** [comment]
I don't know what led you to thinking that..

**Comment by DenialMC** [comment]
then you have no brain

**Comment by vincent15k** [comment]
LOL k

**Comment by DenialMC** [comment]
should i warn you about something

**Comment by vincent15k** [comment]
Go for it.

**Comment by DenialMC** [comment]
just because im not a bitch like u

**Comment by DenialMC** [comment]
one of your developers ratted the server

**Comment by vincent15k** [comment]
pls

**Comment by DenialMC** [comment]
so format your PC

**Comment by DenialMC** [comment]
no im serious format your PC

**Comment by vincent15k** [comment]
My security would've exploded.

**Comment by DenialMC** [comment]
not if it's fud

**Comment by vincent15k** [comment]
Tell me the file then?

**Comment by DenialMC** [comment]
astrond.exe is super sketchy

**Comment by vincent15k** [comment]
Thanks I guess lol

**Comment by DenialMC** [comment]
i dont trust it at all

**Comment by vincent15k** [comment]
I'll check it out

**Comment by DenialMC** [comment]
good

**Comment by vincent15k** [comment]
thank you dan and the tts team

**Comment by DenialMC** [comment]
ur welcome

**Comment by limitrzr** [comment]
This argument is pointless, you're a terrible staff member to argue to another Toontown server. You should support TTCY, even if we did use your code. You should wish us luck, and if that's a serious problem then ignore us. We don't go to you and do things to your server, why are you? Thank you for the warning, we'll look into it.

**Comment by DenialMC** [comment]
now go back to doing your thing with the stolen  features

**Comment by vincent15k** [comment]
^^

**Comment by DenialMC** [comment]
because I am mad. i spent a bunch of time working on the game

**Comment by DenialMC** [comment]
you just swooped it away

**Comment by DenialMC** [comment]
claimed it as yours

**Comment by vincent15k** [comment]
We've added our own things, sen in pictures.

**Comment by DenialMC** [comment]
dude if you havent shown the new CEO i wouldnt have suspected at all

**Comment by DenialMC** [comment]
i dont care did you get permission from me or was TTS open source???

**Comment by DenialMC** [comment]
neither

**Comment by vincent15k** [comment]
New CEO was made by us.

**Comment by DenialMC** [comment]
yes

**Comment by vincent15k** [comment]
Thank you.

**Comment by DenialMC** [comment]
but i know the  changes i made to the game

**Comment by DenialMC** [comment]
the nametag stacking ticked me off

**Comment by DenialMC** [comment]
you shouldnt have posted that

**Comment by limitrzr** [comment]
Just for the record, we have no problem admitting that we used TTS code. Though, I don't feel like you should be arguing with us about this. I understand you're upset at us for using your code, but we still have credited your server.

**Comment by DenialMC** [comment]
no

**Comment by DenialMC** [comment]
stop using the code

**Comment by vincent15k** [comment]
We based off the verison I had when kicked.

**Comment by vincent15k** [comment]
And added other features.

**Comment by DenialMC** [comment]
NOOOOOOOOOOO you didn't.

**Comment by DenialMC** [comment]
http://prntscr.com/86t8iy dude you got kicked way before this.

**Comment by DenialMC** [comment]
stop stating lies...

**Comment by DenialMC** [comment]
I love how you brainwash your own staff

**Comment by DenialMC** [comment]
into hating TTS

**Comment by vincent15k** [comment]
I'll remove that if wanted.

**Comment by limitrzr** [comment]
I don't hate TTS, I respect you guys. I mean, our server is based off of your's, but what I dislike is that you're arguing with us for using your code, and crediting it.

**Comment by DenialMC** [comment]
no remove everything thatts TTS

**Comment by DenialMC** [comment]
No

**Comment by DenialMC** [comment]
you can use this code if it was open source or i gave you permission..

**Comment by DenialMC** [comment]
I haven't

**Comment by DenialMC** [comment]
you STOLE it from us.

**Comment by DenialMC** [comment]
also do you think i was that guy who posted the video with the illuminati stuff? that wasnt me

**Comment by vincent15k** [comment]
http://prntscr.com/86t8ef | "Mature Staff" - TTS 2k15

**Comment by DenialMC** [comment]
further proof you have our repo

**Comment by vincent15k** [comment]
And, we'll remove what is yours.

**Comment by DenialMC** [comment]
dude I cleaned up the entire code

**Comment by Virnios** [comment]
vincent, that has nothing to do with mature staff. just because of some commits doesn't proof they are immature. loool

**Comment by DenialMC** [comment]
I made a BUNCH of new features

**Comment by vincent15k** [comment]
No, I found it from a non staff friend :P

**Comment by DenialMC** [comment]
NON STAFF. Yes it's super staff because it was done for Crystal.

**Comment by DenialMC** [comment]
we have over 1200 commits on Stride we touched EVERY SINGLE FILE

**Comment by DenialMC** [comment]
you cant just 'remove everything from TTS'

**Comment by DenialMC** [comment]
http://github.com/ToontownInfinite/src <- LOOK that's open source

**Comment by vincent15k** [comment]
I've still seen bits of infinite in you source.

**Comment by DenialMC** [comment]
feel free to use that

**Comment by DenialMC** [comment]
infinite is open source

**Comment by DenialMC** [comment]
if we use it and give credit that's OK

**Comment by DenialMC** [comment]
but you have no right to use our source

**Comment by DenialMC** [comment]
in the first place

**Comment by DenialMC** [comment]
no credit or credit

**Comment by vincent15k** [comment]
Good.

**Comment by DenialMC** [comment]
then go use TTI source

**Comment by DenialMC** [comment]
don't use our source.

**Comment by DenialMC** [comment]
basically our source got leaked again because you stupid people used it for your own server which got leaked geez

**Comment by vincent15k** [comment]
I'm using what I had when I was there.

**Comment by DenialMC** [comment]
no you aren't.

**Comment by DenialMC** [comment]
You have nametag stacking

**Comment by vincent15k** [comment]
I'll leave it at that.

**Comment by DenialMC** [comment]
Admin nametags

**Comment by DenialMC** [comment]
Delete all buttons. TVs.

**Comment by DenialMC** [comment]
all that stuff was implemented AFTER your departure

**Comment by vincent15k** [comment]
We don't have TVs

**Comment by DenialMC** [comment]
you leaked our source a SECOND TIME

**Comment by limitrzr** [comment]
We don't have TVs...

**Comment by DenialMC** [comment]
TvToPosScale = {
 1530: ((-1.15, -0.5, 1.1), (2.5, 1.7, 1.4)),
 1531: ((-2.3, -0.2, 1.6), (5, 5, 5)),
 1532: ((-7, -0.2, 1.8), (15, 10, 8.5)) 
}

**Comment by DenialMC** [comment]
https://github.com/DenialMC/Toontown-Crystal-New/blob/master/src/toontown/catalog/CatalogFurnitureItem.py YES YOU DO

**Comment by DenialMC** [comment]
https://github.com/DenialMC/Toontown-Crystal-New/blob/master/src/toontown/catalog/CatalogFurnitureItem.py#L1084 YES YOU DO

**Comment by DenialMC** [comment]
WE DONT HAVE TVS
- toontown crystal 2k15

**Comment by DenialMC** [comment]
we are using the source from when i was kicked
- foster 2k15

**Comment by limitrzr** [comment]
I haven't seen it in-game.. I'm not a developer but, I just haven't seen it at all.

**Comment by DenialMC** [comment]
no

**Comment by DenialMC** [comment]
everything you say

**Comment by vincent15k** [comment]
Notice it's on your repo

**Comment by DenialMC** [comment]
is a goddamned lie

**Comment by DenialMC** [comment]
Vincent

**Comment by vincent15k** [comment]
Not ours

**Comment by DenialMC** [comment]
I will find the commit where you guys added it to Crystal.

**Comment by DenialMC** [comment]
Not me. YOU GUYS

**Comment by DenialMC** [comment]
WHO IS JOSH ZIMMER

**Comment by DenialMC** [comment]
isnt he like the ttf leader or something

**Comment by DenialMC** [comment]
nice it just got deleted

**Comment by DenialMC** [comment]
now you are forming your strategy

**Comment by DenialMC** [comment]
how do you want to defend yourself when it's pretty well known

**Comment by DenialMC** [comment]
that you used our code. im not happy about it, it got leaked once by you, and now ttcy got leaked and by extension our code. AGAIN.

**Comment by DenialMC** [comment]
you were being a MAJOR asshole on IRC telling everybody that 'TTS has a rat' apparently.

**Comment by DenialMC** [comment]
claiming OUR features as yours.

**Comment by DenialMC** [comment]
brainwashing your own staff to hate TTS.

**Comment by DenialMC** [comment]
why? heil jackson vince foster

**Comment by limitrzr** [comment]
He never said TTS had a rat, I'm sure of it. I also don't "heil" Vince. I respect him, sure, but no one is really that godly.

**Comment by DenialMC** [comment]
he never said tts had a rat?

**Comment by DenialMC** [comment]
oh god

**Comment by DenialMC** [comment]
yes he did

**Comment by DenialMC** [comment]
he spreads lies to his own goddamn friends

**Comment by limitrzr** [comment]
If he did, my apologies, since I haven't seen it.

**Comment by DenialMC** [comment]
you havent seen a lot of stuff apparently.

**Comment by DenialMC** [comment]
TTCY is a stolen server.

**Comment by vincent15k** [comment]
I'm just sitting here laughing at Toontown Stride's decisions on hiring you.

**Comment by DenialMC** [comment]
Im their best dev

**Comment by DenialMC** [comment]
im experienced

**Comment by Virnios** [comment]
^

**Comment by vincent15k** [comment]
You were fired for calling members feminazis

**Comment by DenialMC** [comment]
thats why i was hired

**Comment by DenialMC** [comment]
Why were you hired then?

**Comment by DenialMC** [comment]
I have troubles understanding why stride hired you

**Comment by vincent15k** [comment]
Me and Volt had talked about never hiring you, because members did not like you, the truth hurts.

**Comment by Spiderlover** [comment]
@DenialMC shouldn't you be leaking TTI's source code right now

**Comment by DenialMC** [comment]
i was there in february when we got the idea to make stride.. LOOOL

**Comment by vincent15k** [comment]
Baru was about to quit because of what you said.

**Comment by DenialMC** [comment]
Spiderlover craigy already did that. Sorry.

**Comment by DenialMC** [comment]
Dude I wonder where did your SOS deleting feature come from!

**Comment by DenialMC** [comment]
If not TTI! The text scale is the same position is same even the frame size is the EXACT SAME

**Comment by vincent15k** [comment]
**OPEN SOURCE**

**Comment by vincent15k** [comment]
You said it yourself, bud.

**Comment by DenialMC** [comment]
THE NEW TTI SOURCE IS NOT

**Comment by DenialMC** [comment]
Are you stupid?

**Comment by vincent15k** [comment]
Also https://www.virustotal.com/en/file/4d62485f2e1e7f32c6fc0bdd4a788a6a55cc4a9894f00422d6aa6ba65d77fd65/analysis/1440098260/

**Comment by DenialMC** [comment]
The old TTI source is opensource. It's on Github. their current test server is NOT.

**Comment by Loudrob** [comment]
fooster the new tti source is not open source you don't have the right to use that

**Comment by vincent15k** [comment]
"astron is ratted"

**Comment by DenialMC** [comment]
you dont have the right to use our code either...

**Comment by Loudrob** [comment]
neither sources are open source so your entire game is literally 100% stolen code

**Comment by DenialMC** [comment]
Vincent i dont have definitive proof. But it's super sketchy. Thought yo should know.

**Comment by DenialMC** [comment]
I don't care if you did many changes to your game

**Comment by DenialMC** [comment]
Half of your commits is adding preferences.json and PYC files

**Comment by vincent15k** [comment]
Thanks.

**Comment by DenialMC** [comment]
Which shouldnt be in the repo in the first place

**Comment by Loudrob** [comment]
now why are you using github comments as an instant messager

**Comment by DenialMC** [comment]
You're just filling that space to look 'legit'

**Comment by DenialMC** [comment]
because i am not adding this stupid person on skype

**Comment by vincent15k** [comment]
Because someone won't add me on Skype, or message me.

**Comment by Loudrob** [comment]
you can give all the credit you want to tts/tti/ttr/tth/ttn but you were never given permission

**Comment by DenialMC** [comment]
you havent asked me either so both of us are guilty in that

**Comment by Spiderlover** [comment]
@DenialMC you hate TTR as well?

**Comment by DenialMC** [comment]
loudrob is right plus none of these sources are open source and im talking about the new TTI source.

**Comment by DenialMC** [comment]
TTR is bae

**Comment by vincent15k** [comment]
Honestly, I don't see why I'm still here.

**Comment by DenialMC** [comment]
Why would you suggest I don't like TTR

**Comment by limitrzr** [comment]
Don't act like your code wasn't stolen, TTI stole code from TTR, remember?

**Comment by Loudrob** [comment]
TTR is the reason any of these servers exist

**Comment by DenialMC** [comment]
then vince why are u still here

**Comment by DenialMC** [comment]
limitrzr why is your server stealing that code from TTR then

**Comment by Spiderlover** [comment]
and TTR stole code from Disney, your point?

**Comment by DenialMC** [comment]
my point is

**Comment by Loudrob** [comment]
our point is we actually are pissed and have the right to be

**Comment by DenialMC** [comment]
TTR stole code from disney  yes

**Comment by Loudrob** [comment]
disney chose not to care

**Comment by DenialMC** [comment]
but the game was ABANDONED

**Comment by DenialMC** [comment]
nobody cared about toontown

**Comment by limitrzr** [comment]
Yeah, but TTR never got so pissed off at TTI from their stolen code.

**Comment by Loudrob** [comment]
they did get pissed off

**Comment by DenialMC** [comment]
then whats your point

**Comment by Loudrob** [comment]
never publicly though

**Comment by DenialMC** [comment]
im sure they got as pissed off like us right now if not more

**Comment by DenialMC** [comment]
Whatever that was an EARLY build of the game

**Comment by DenialMC** [comment]
it didnt even have cogs.

**Comment by DenialMC** [comment]
But you are stealing our game when its ALMOST BASICALLY READY FOR RELEASE

**Comment by DenialMC** [comment]
WITH A BUNCH OF FEATURES

**Comment by DenialMC** [comment]
also josh zimmer

**Comment by vincent15k** [comment]
almost basically

**Comment by CodeAnGo** [comment]
^^^ For the record, We're currently working to move from Astron to a daemon me and another team member are building.

Also, why care about astrond potentially being a rat (Even though it's not, do you even know how Fudding works?) since astron is meant for server side only? It poses no risk to users...

**Comment by Loudrob** [comment]
fooster the only reason your server exists is because you think you were unfairly kicked from tts, which we had the right to kick you if we didn't trust you anyway

**Comment by DenialMC** [comment]
it poses the risk to your own staff

**Comment by DenialMC** [comment]
stop working on this game

**Comment by DenialMC** [comment]
also there is nothing wrong wiht using astron since astron is open source.

**Comment by DenialMC** [comment]
bunch of other games use it such as POTCO

**Comment by Loudrob** [comment]
besides, you just proved that you have not changed and that you are just as bad as you were in july 2014 by getting all pissy about getting kicked from tts

**Comment by CodeAnGo** [comment]
You're the only one who said astron is bad?

**Comment by DenialMC** [comment]
quote me where did i say astron was bad

**Comment by DenialMC** [comment]
or your statement is invalid

**Comment by Virnios** [comment]
he said it was sketchy, not bad.

**Comment by DenialMC** [comment]
i said that dubito's astron BUILD is sketchy

**Comment by CodeAnGo** [comment]
You said that the astron has malware which was fudded, let me ask you, how long do you think fudding works?

**Comment by Loudrob** [comment]
let me ask you something important

**Comment by Loudrob** [comment]
...why would you hire dubito ever

**Comment by CodeAnGo** [comment]
Go for it

**Comment by Loudrob** [comment]
hf.dubito hackforums for the win!1111

**Comment by DenialMC** [comment]
not Astron/Astron but dubito's astron its 5 mb a normal build is 800kb

**Comment by DenialMC** [comment]
its SUPER SKETCHY

**Comment by Loudrob** [comment]
you realize dubito is the same guy who got mad and tried to swat other tth staff members while he was on their team

**Comment by vincent15k** [comment]
Why would you hire DenialMC

**Comment by Loudrob** [comment]
so ah good luck with him

**Comment by DenialMC** [comment]
Astron is good the astron team did good with that.. i never said astron was bad

**Comment by CodeAnGo** [comment]
It's not sketchy at all, build astron yourself. Look at the file size

**Comment by Loudrob** [comment]
because he actually know's what hes doing?

**Comment by vincent15k** [comment]
Tell me, what is he doing

**Comment by Spiderlover** [comment]
and he's a rude staff member that insults the entire staff

**Comment by Loudrob** [comment]
developing the game

**Comment by DenialMC** [comment]
I made the TTS features. The features that you are living off and claiming as your own

**Comment by DenialMC** [comment]
i made this game

**Comment by CodeAnGo** [comment]
I find it hilarious, if you guys knew what you were doing with astron, for example, building it yourself, you would know the file size is around 5mb

**Comment by DenialMC** [comment]
it isnt 5 mb

**Comment by Loudrob** [comment]
haha 5mb

**Comment by DenialMC** [comment]
not at all

**Comment by Loudrob** [comment]
mine is 847 kb

**Comment by CodeAnGo** [comment]
With SSL?

**Comment by DenialMC** [comment]
ask astron on IRC

**Comment by vincent15k** [comment]
Dan Zach made it

**Comment by Loudrob** [comment]
dude its built with ssl by default

**Comment by Loudrob** [comment]
zach never built astron

**Comment by DenialMC** [comment]
then why does it say dubito's custom build

**Comment by DenialMC** [comment]
also nice zach gates in on ur team? he's wasting his time he shouldnt hve quit TTS

**Comment by Loudrob** [comment]
the reason your's is 5mb is because dubito either binded another program to it or built it completely wrongly

**Comment by CodeAnGo** [comment]
For the record, why would you guys care about Toontown Crystal's files anyway?

**Comment by Loudrob** [comment]
...because they're ours?

**Comment by DenialMC** [comment]
because its using TTS source.

**Comment by Virnios** [comment]
cause its tts code

**Comment by DenialMC** [comment]
its OUR CODE

**Comment by DenialMC** [comment]
not yours

**Comment by DenialMC** [comment]
you have no right to use it

**Comment by Spiderlover** [comment]
technically TTI and TTS are the same game just different coding

**Comment by DenialMC** [comment]
are you serious

**Comment by Spiderlover** [comment]
yep

**Comment by Virnios** [comment]
bullshit

**Comment by Loudrob** [comment]
don't even try to bring up that argument about replacing the code, i very well know that all of your commits are the worst commits ever

**Comment by DenialMC** [comment]
well... i dont know how to reply to that level of stupidity

**Comment by Loudrob** [comment]
you reverted to the python dna parser

**Comment by Loudrob** [comment]
cause the c++ one "didnt work"

**Comment by DenialMC** [comment]
more like 'how do i compile libpandadnA?'

**Comment by DenialMC** [comment]
why dont you have a .gitignore file

**Comment by DenialMC** [comment]
brb 10 mins

**Comment by vincent15k** [comment]
libpanda*

**Comment by CodeAnGo** [comment]
Are you pissed that you think we stole code, or that we are doing better then you... Just saying ;)

**Comment by Loudrob** [comment]
libpandadna****

**Comment by Loudrob** [comment]
yes we totally think stealing tti code = doing better

**Comment by CodeAnGo** [comment]
Just let the better server prevail

**Comment by Loudrob** [comment]
considering you only have 1 half-competent developer doing all of your launcher deployment and web work for you

**Comment by CodeAnGo** [comment]
And who's that?

**Comment by Loudrob** [comment]
i wouldnt call that succeeding

**Comment by Loudrob** [comment]
dubito

**Comment by Loudrob** [comment]
lol

**Comment by Virnios** [comment]
hey

**Comment by vincent15k** [comment]
ayy

**Comment by CodeAnGo** [comment]
You see, we don't know who does each aspect of your game, because we are focusing on ours. Perhaps you should do the same?

**Comment by Loudrob** [comment]
its hard to not talk to a server that happens to be taking the easy way out

**Comment by Loudrob** [comment]
using tts source and tti source

**Comment by Loudrob** [comment]
merging em

**Comment by Spiderlover** [comment]
yeah, instead of bashing us every day, like one of your buddies Michael_SK.

**Comment by Loudrob** [comment]
and claiming to have a finished game

**Comment by Loudrob** [comment]
we have seen various evidence that you are indeed using the latest tti source and tts code

**Comment by Loudrob** [comment]
anybody besides you 3 on your team denying it is brainwashed

**Comment by vincent15k** [comment]
I don't see why you have to be immature and insult us, when you could be focusing on making your game better.

**Comment by Loudrob** [comment]
trust me we are focusing on that

**Comment by Loudrob** [comment]
i call this my "break time"

**Comment by CodeAnGo** [comment]
Our game is finished, we're going into alpha next month.
We have a custom daemon from scratch,
We have a fully functional game server, hosted on one of the most reliable platforms,
We have a fully functional compiler.

You just have a bunch of people who instead of working on their own game, decide to try to bash and attack us.

**Comment by Loudrob** [comment]
alpha != finished

**Comment by Loudrob** [comment]
lol

**Comment by Loudrob** [comment]
finished = release

**Comment by Spiderlover** [comment]
@DenialMC @Loudrob if you don't want your game to be better, go ahead and delete your source code

**Comment by CodeAnGo** [comment]
Nope, but it's a hell of a lot further then you guys are

**Comment by Loudrob** [comment]
where did i say i didn't want my game to be better

**Comment by Loudrob** [comment]
LOL

**Comment by Loudrob** [comment]
you don't even know how far we are right now

**Comment by Loudrob** [comment]
unless you have our latest source..... ;)

**Comment by CodeAnGo** [comment]
We don't care, we're focusing on our game

**Comment by Virnios** [comment]
i want popcorn, this is some great movie.

**Comment by Spiderlover** [comment]
your game probably isn't better since you and your team spend all day and all night bashing us instead of developing your server.

**Comment by Loudrob** [comment]
haha

**Comment by CodeAnGo** [comment]
If you guys don't mind, we're a little busy getting our game service topology sorted

**Comment by Loudrob** [comment]
but be warned that when anybody sees that you have things such as brrrgh fog/models from tti

**Comment by Loudrob** [comment]
it won't end well.

**Comment by vincent15k** [comment]
Who says we can't put fog in a snowy playground?

**Comment by Loudrob** [comment]
its not the fact that you have it

**Comment by DenialMC** [comment]
its tti branded fog

**Comment by Loudrob** [comment]
its the fact that you took it from tti

**Comment by DenialMC** [comment]
i dont care if you hve fog in a snowy plyaground but it's not your fog

**Comment by DenialMC** [comment]
ok  heres the deal

**Comment by Loudrob** [comment]
im fine with your features as long as you actually... make them yourself

**Comment by DenialMC** [comment]
as the majority commitholder

**Comment by DenialMC** [comment]
i will give you permission to use our source code and features

**Comment by DenialMC** [comment]
if you pay the tt stride team $2500

**Comment by DenialMC** [comment]
you do that and I have no problems use our code all day

**Comment by CodeAnGo** [comment]
I'd be careful there @DenialMC 
Once you start requesting money for things you don't own rights to, things can get a little technical

**Comment by DenialMC** [comment]
also crispy no

**Comment by Loudrob** [comment]
he owns the rights to his own code

**Comment by Loudrob** [comment]
that money is there for the code he wrote

**Comment by DenialMC** [comment]
I'd be careful there Dubito

**Comment by DenialMC** [comment]
I am selling you my work

**Comment by DenialMC** [comment]
That I have put to the TTI source code called Toontown Stride

**Comment by DenialMC** [comment]
i am not selling you TTI's and TTR's work but MINE

**Comment by DenialMC** [comment]
Wanna make TTCY? OK but revert to the TTI source please. Do not use any of our features or cleaned up code.

**Comment by DenialMC** [comment]
Or pay me and I don't care if you use my code.

**Comment by CodeAnGo** [comment]
You realise you just broke your own argument.

If you take TTI's source and add stuff too it it magically becomes TTS and is all "MINE"

However, when we take TTS's extremely old source, add stuff too it, it magically becomes stolen?

**Comment by DenialMC** [comment]
it's not an extremely old source. It's a source from 26 days ago.

**Comment by DenialMC** [comment]
April/May source? OK. Go ahead use that.

**Comment by DenialMC** [comment]
That would be the extremely old source

**Comment by DenialMC** [comment]
This is an extremely RECENT source.

**Comment by DenialMC** [comment]
from 26 days ago.

**Comment by Loudrob** [comment]
dubito the difference: tti actually released their source as an open-sourced project

**Comment by CodeAnGo** [comment]
Also, the files contained copyrighted material to Disney Interactive Media
Group, so you can't legally charge money, or it breeches fair use...

**Comment by DenialMC** [comment]
Blah blah blah I am selling you MY work not Disney's work or TTI's or TTR's work.

**Comment by DenialMC** [comment]
I made changes to the game

**Comment by Loudrob** [comment]
we aren't charging money for any of disney's, ttr's, or tti's work

**Comment by Loudrob** [comment]
only the code that has been made by daniel

**Comment by DenialMC** [comment]
I own these changes

**Comment by Loudrob** [comment]
if you dont want to pay for that then just simply use tti's source

**Comment by Loudrob** [comment]
there isn't really an issue with you using tti's source

**Comment by CodeAnGo** [comment]
The features we have in the game will be staying, however we are going to be rolling back to TTI's source and re-implementing said features, alongside the Magnus Daemon

**Comment by DenialMC** [comment]
Do not reimplement said features. those are my features.

**Comment by Loudrob** [comment]
only implement your features

**Comment by Loudrob** [comment]
not dan's

**Comment by Loudrob** [comment]
any of the ones he had strip from the game

**Comment by CodeAnGo** [comment]
Re code and re implement I meant

**Comment by CodeAnGo** [comment]
You have the right to your code, not the idea's behind it

**Comment by Loudrob** [comment]
also revert to TTI's DECEMBER source

**Comment by Virnios** [comment]
pay me 2 dollars and ill give you ideas

**Comment by Loudrob** [comment]
because if you use their latest one you'll just have more problems with them ;)

**Comment by vincent15k** [comment]
Here, just let me also hand over my credit card number and SSN.

**Comment by Loudrob** [comment]
and also, i know you probably can't resist the urge to just use tti's gardening game tables parties etc.. but if you don't ever want problems with them either you should probably make them yourselves

**Comment by CodeAnGo** [comment]
We may even try a base from scratch, we're still discussing different ideas, we know the logistics behind each choice, but we don't need you harassing us, we wouldn't release a game with your source, that's just a dick move, we never planned to. We only used it as a base for development, so we can move onto a open platform. It would have been done and decided sooner if you guys didn't harass us

**Comment by Loudrob** [comment]
you shouldn't have advertised your content before you switched off of our source either then

**Comment by Loudrob** [comment]
we were at first going to leave you alone but flaunting around your content and brainwashing your staff members can't be left alone

**Comment by Loudrob** [comment]
if you do what we requested we have no problems with you and you can continue what you're doing

**Comment by CodeAnGo** [comment]
For the record, we don't need your permission to continue.

We were already planning to remove everything related to TTS, but you guys don't bother to ask for our side of things, only go on what gets leaked or told by salty members

**Comment by DenialMC** [comment]
then stop planning and DO IT

**Comment by CodeAnGo** [comment]
Stop harassing us and maybe we'd have time?
Notice how I got the whole team to stop commenting and get back to work, it's called organisation.

**Comment by CodeAnGo** [comment]
Now, if we are done here, I have a topology to design and implement - https://gyazo.com/07bc1c1076502e2d0cc3ecb8c9090334

**Comment by DenialMC** [comment]
ok have fun

**Comment by Virnios** [comment]
thx

**Comment by ToontownModder101** [comment]
We should remove all Stride features tbh, and the new boss cog cutscenes, and laff and gag NPCs in the Cog HQ's, make the game less like stride and besides I have been being creative with boss cogs recently.
